In [2]:
import pandas as pd

In [3]:
def output_challenge_eliminated_df():
    with open("challenge-eliminated-list.txt") as f:
        content = f.readlines()
    content = [x.strip().split(',') for x in content]
    
    # Clean Text
    for i in range(10):
        content[i][0] = 'Tribe ' + content[i][0]
    for i in range(len(content)):
        content[i][1] = content[i][1].title()[1:len(content[i][1]) - 1]
    for i in range(10,18):
        content[i][0] = content[i][0].title()[1:len(content[i][0]) - 1]

    df = pd.DataFrame(content, columns=['Challenge Winner', 'Eliminated Contestant'])
    return df

def output_contestant_resumes_df():
    with open("contestant-resumes-list.txt") as f:
        content = f.readlines()
    content
    content = [x.strip().split(',') for x in content]

    df = pd.DataFrame(content, columns=['Contestant', 'Tribe', 'Finish', '# Individual Challenges Won', 'Physical'])
    return df

def output_voting_histories_df():
    with open("voting-histories-list.txt") as f:
        content = f.readlines()
    content = [x.strip().split(',') for x in content]
    target_length = len(content[0])
    rows = []

    # pad rows
    for i in range(len(content)):
        length = len(content[i])
        content[i].extend([""] * (target_length - length))
        rows.append(content[i].pop(0))

    for i in range(len(content)):
        for j in range(len(content[0])):
            if content[i][j] == 'nobody':
                content[i][j] = '-'
    df = pd.DataFrame(content, index=rows, columns=rows[:1:-1])
    return df

In [4]:
output_challenge_eliminated_df()

   Challenge Winner Eliminated Contestant
0           Tribe 0         Contestant 10
1           Tribe 1          Contestant 2
2           Tribe 1          Contestant 0
3           Tribe 0         Contestant 11
4           Tribe 1          Contestant 8
5           Tribe 0         Contestant 15
6           Tribe 0         Contestant 16
7           Tribe 1          Contestant 9
8           Tribe 1          Contestant 3
9           Tribe 1          Contestant 7
10    Contestant 12          Contestant 1
11    Contestant 19          Contestant 6
12    Contestant 12          Contestant 4
13    Contestant 19          Contestant 5
14    Contestant 13         Contestant 14
15    Contestant 19         Contestant 18
16    Contestant 19         Contestant 17
17    Contestant 12         Contestant 19

In [5]:
output_contestant_resumes_df()

   Contestant Tribe Finish # Individual Challenges Won Physical
0          10     1     20                           0        0
1           2     0     19                           0        1
2           0     0     18                           0        2
3          11     1     17                           0        1
4           8     0     16                           0        3
5          15     1     15                           0        1
6          16     1     14                           0        3
7           9     0     13                           0        3
8           3     0     12                           0        4
9           7     0     11                           0        4
10          1     0     10                           0        9
11          6     0      9                           0        8
12          4     0      8                           0        5
13          5     0      7                           0        5
14         14     1      6                           0        9
15         18     1      5                           0        9
16         17     1      4                           0        6
17         19     1      3                           4        9
18         13     1      0                           1        3
19         12     1      0                           3        6

In [6]:
output_voting_histories_df()

,10,2,0,11,8,15,16,9,3,7,1,6,4,5,14,18,17,19
13,(contestant 10),-,-,(contestant 15),-,(contestant 15),(contestant 16),-,-,-,(contestant 1),(contestant 6),(contestant 5),(contestant 5),(contestant 14),(contestant 18),(contestant 12),(contestant 19)
12,(contestant 10),-,-,(contestant 15),-,(contestant 15),(contestant 16),-,-,-,(contestant 1),(contestant 6),(contestant 4),(contestant 5),(contestant 18),(contestant 18),(contestant 17),(contestant 19)
19,(contestant 10),-,-,(contestant 11),-,(contestant 15),(contestant 16),-,-,-,(contestant 1),(contestant 6),(contestant 4),(contestant 5),(contestant 14),(contestant 18),(contestant 17),(contestant 13)
17,(contestant 10),-,-,(contestant 11),-,(contestant 15),(contestant 13),-,-,-,(contestant 1),(contestant 6),(contestant 4),(contestant 5),(contestant 19),(contestant 18),(contestant 12),
18,(contestant 10),-,-,(contestant 11),-,(contestant 15),(contestant 13),-,-,-,(contestant 1),(contestant 6),(contestant 4),(contestant 5),(contestant 14),(contestant 17),,
14,(contestant 10),-,-,(contestant 11),-,(contestant 15),(contestant 16),-,-,-,(contestant 1),(contestant 6),(contestant 5),(contestant 5),(contestant 19),,,
5,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 9),(contestant 3),(contestant 7),(contestant 19),(contestant 18),(contestant 18),(contestant 18),,,,
4,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 9),(contestant 7),(contestant 7),(contestant 14),(contestant 14),(contestant 18),,,,,
6,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 9),(contestant 3),(contestant 7),(contestant 14),(contestant 18),,,,,,
1,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 9),(contestant 3),(contestant 7),(contestant 14),,,,,,,
7,-,(contestant 2),(contestant 0),-,(contestant 9),-,-,(contestant 9),(contestant 3),(contestant 5),,,,,,,,
3,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 9),(contestant 7),,,,,,,,,
9,-,(contestant 2),(contestant 0),-,(contestant 8),-,-,(contestant 3),,,,,,,,,,
16,(contestant 10),-,-,(contestant 11),-,(contestant 15),(contestant 13),,,,,,,,,,,
15,(contestant 10),-,-,(contestant 11),-,(contestant 16),,,,,,,,,,,,
8,-,(contestant 2),(contestant 0),-,(contestant 9),,,,,,,,,,,,,
11,(contestant 10),-,-,(contestant 15),,,,,,,,,,,,,,
0,-,(contestant 2),(contestant 9),,,,,,,,,,,,,,,
2,-,(contestant 0),,,,,,,,,,,,,,,,
10,(contestant 15),,,,,,,,,,,,,,,,,