In [66]:
import csv
import pandas as pd
import pprint
pp = pprint.PrettyPrinter(indent=4)

In [70]:
pd.read_csv("challenge-eliminated-list.csv")

   challenge-winner eliminated-contestant
0                 1        (contestant 8)
1                 1        (contestant 1)
2                 1        (contestant 9)
3                 1        (contestant 3)
4                 0       (contestant 18)
5                 0       (contestant 11)
6                 0       (contestant 12)
7                 0       (contestant 14)
8                 0       (contestant 19)
9                 0       (contestant 16)
10  (contestant 10)       (contestant 15)
11   (contestant 2)       (contestant 13)
12  (contestant 17)        (contestant 2)
13   (contestant 5)       (contestant 17)
14   (contestant 4)        (contestant 7)
15   (contestant 0)        (contestant 5)
16   (contestant 6)       (contestant 10)
17   (contestant 0)        (contestant 6)

In [71]:
pd.read_csv("contestant-resumes.csv")

,contestant,tribe,finish,individual-challenge-wins,mental,physical,social
0,8,0,20,0,1,3,5
1,1,0,19,0,1,3,6
2,9,0,18,0,5,6,0
3,3,0,17,0,6,7,2
4,18,1,16,0,3,5,1
5,11,1,15,0,4,5,9
6,12,1,14,0,8,6,5
7,14,1,13,0,4,3,2
8,19,1,12,0,5,5,3
9,16,1,11,0,4,5,5
10,15,1,10,0,7,4,5
11,13,1,9,0,5,5,8
12,2,0,8,1,3,10,5
13,17,1,7,1,5,5,8
14,7,0,6,0,7,5,5
15,5,0,5,1,5,7,4
16,10,1,4,1,4,4,6
17,6,0,3,1,5,2,5
18,4,0,0,1,4,4,2
19,0,0,0,2,4,4,5

In [72]:
pd.read_csv("voting-histories.csv", index_col='contestant').fillna('')

,8 (8-2),1 (5-4),9 (4-4),3 (4-3),18 (7-3),11 (7-2),12 (7-1),14 (6-1),19 (5-1),16 (4-1),15 (6-4),13 (7-2),2 (7-1),17 (6-1),7 (5-1),5 (4-1),10 (3-1),6 (2-1),4,0
contestant,,,,,,,,,,,,,,,,,,,,
4,8,1,9,3,-,-,-,-,-,-,15,13,2,17,7,5,10,6,,
0,8,1,9,3,-,-,-,-,-,-,15,13,2,17,7,5,10,6,,
6,8,1,9,3,-,-,-,-,-,-,15,13,2,17,7,5,10,4,,
10,-,-,-,-,18,11,12,14,19,16,2,17,2,17,7,5,0,,,
5,8,4,4,4,-,-,-,-,-,-,15,13,2,17,7,10,,,,
7,8,4,4,4,-,-,-,-,-,-,15,13,2,17,5,,,,,
17,-,-,-,-,18,11,12,14,19,16,2,13,2,7,,,,,,
2,8,1,9,3,-,-,-,-,-,-,15,13,7,,,,,,,
13,-,-,-,-,18,11,12,14,19,16,2,17,,,,,,,,
15,-,-,-,-,18,11,12,14,19,16,2,,,,,,,,,
16,-,-,-,-,18,11,12,14,19,10,,,,,,,,,,
19,-,-,-,-,18,11,12,14,16,,,,,,,,,,,
14,-,-,-,-,18,11,12,19,,,,,,,,,,,,
12,-,-,-,-,14,14,14,,,,,,,,,,,,,
11,-,-,-,-,14,14,,,,,,,,,,,,,,
18,-,-,-,-,14,,,,,,,,,,,,,,,
3,8,4,4,4,,,,,,,,,,,,,,,,
9,4,1,4,,,,,,,,,,,,,,,,,
1,8,4,,,,,,,,,,,,,,,,,,
8,4,,,,,,,,,,,,,,,,,,,